name: Publish API docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  codox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: "2.11.2"
      - name: Generate Codox
        run: lein codox
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
